version: "3.3"
   
services:
  db:
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
    env_file:
      ./backend/.env
  backend:
    image: shopsale_backend
    env_file:
      ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/usr/app/backend
    ports:
      - "8001:8001"
    depends_on:
      - db
      - migration
  migration:
    image: shopsale_backend
    env_file:
      ./backend/.env
    command: python manage.py migrate
    volumes:
      - ./backend:/usr/app/backend
    depends_on:
      - db
  redis:
    image: redis
    ports:
      - "6379:6379"
  frontend:
    env_file:
      ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/.next
      - /usr/app/frontend/node_modules
