version: "3.3"

services:
  db:
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
    restart: always
    env_file:
      ./backend/.env
    volumes:
      - ./backend/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./backend/.env:/backend/usr/app/.env
      - ./backend/dump.sql:/backend/usr/app/dump.sql
  backend:
    image: shopsale_backend
    env_file:
      ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["/usr/app/backend/wait-for-it.sh", "db:5432", "-t", "5", "--", "python", "manage.py", "runserver", "0.0.0.0:8001"]
    volumes:
      - ./backend:/usr/app/backend
    ports:
      - "8001:8001"
    depends_on:
      - db
  migration:
    image: shopsale_backend
    env_file:
      ./backend/.env
    command: ["/usr/app/backend/wait-for-it.sh", "db:5432", "-t", "5", "--", "python", "manage.py", "migrate"]
    volumes:
      - ./backend:/usr/app/backend
    depends_on:
      - db
      - backend
  redis:
    image: redis
    ports:
      - "6379:6379"
  worker:
    image: shopsale_backend
    command:  bash -c "rm -f -- -celerybeat && celery -A shopapp worker -l INFO"
    env_file:
      ./backend/.env
    volumes:
      - ./backend:/usr/app/backend
    depends_on:
      - backend
  frontend:
    env_file:
      ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/.next
      - /usr/app/frontend/node_modules
