export const FETCH_PRODUCTS = 'SET_PRODUCTS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED'; 

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';

export const ADD_PRODUCT_TO_CARD = 'ADD_PRODUCT_TO_CARD';
export const LOAD_CARTS_SUCCESS = 'LOAD_CARTS_SUCCESS';
export const LOAD_CARTS_FAILED = 'LOAD_CARTS_FAILED';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';

export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL';
export const OPEN_SIGN_IN_MODAL = 'OPEN_SIGN_IN_MODAL';

export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';
export const CLOSE_SIGN_IN_MODAL = 'CLOSE_SIGN_IN_MODAL';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const LOGOUT = 'LOGOUT';

export const LOAD_ADDRESS = 'LOAD_ADDRESS';

export const SET_ALLOW_NEXT_STEP = 'SET_ALLOW_NEXT_STEP'