# Generated by Django 3.1.6 on 2022-02-12 02:56

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211109_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FilePathField(blank=True, null=True, path=shop.models.image_categories_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FilePathField(blank=True, null=True, path=shop.models.image_products_path),
        ),
    ]
