# Generated by Django 3.1.6 on 2022-02-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220212_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
