# Generated by Django 3.1.6 on 2022-02-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220212_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='files/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='files/'),
        ),
    ]
