export const FETCH_PRODUCTS = 'SET_PRODUCTS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED'; 

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
