export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED'; 
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';


export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';